### ISSUE TITLE
Add pagination for feeds checked

### ISSUE THREAD

**Issue by nipuna777** [CUTR-at-USF/gtfs-realtime-validator#13] opened 2015-09-28 16:12 UTC
Add pagination to the feeds checked interface. This will allow the users to navigate to earlier errors. The current interface only shows the first 10 errors.

Back-end has to be changed in order to support this behavior.

**Comment by barbeau** [comment] 2017-04-12 19:25
Closing this as a duplicate of https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/106.

**Closed by barbeau** 2017-04-12 19:25 UTC
Labels: duplicate, enhancement
