### ISSUE TITLE
Add interface for viewing error details

### ISSUE THREAD

**Issue by nipuna777** [CUTR-at-USF/gtfs-realtime-validator#11] opened 2015-09-28 16:06 UTC
Currently, once an error is clicked, the user is taken to the representative JSON. This should be changed to a human readable interface.

**Comment by barbeau** [comment] 2017-04-12 19:20
Closing this as a duplicate of https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/100.

**Closed by barbeau** 2017-04-12 19:20 UTC
Labels: duplicate
